# -*- coding: utf-8 -*-
"""Permeability

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aUKFcnn-u1vpEgr2PRN_j3cdoR2_l9yv
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import files
upoaded=files.upload()

df = pd.read_csv('Pt.csv')
df

plt.style.use('default')
plt.figure(figsize=(12,4))
df.plot( y='pressure', x='time')
plt.grid()
plt.title('Cartesian plot : Drawdown test')

plt.style.use('default')
plt.figure(figsize=(12,4))
plt.semilogx(df['time'], df['pressure'], lw=1 )
plt.grid()
plt.title('Semilog plot : Drawdown test')

import numpy as np

pi=2760 #psi
df['delP']=np.abs(pi-df['pressure'])
df['d(delP)']=np.zeros(len(df))
df['d(delP)'].iloc[1:] = np.abs(np.diff(df['delP']))
df['d(delP)'].iloc[1:] 
df['dt']=np.zeros(len(df))
df['dt'].iloc[1:]=np.diff(df['time'])
df['dt'].iloc[1:]
#p'=t*dp/dt
df['Pdash']= np.zeros(len(df))
df['Pdash'].iloc[:]=df['time']*(df['d(delP)']/df['dt'])

df.head()

plt.style.use('default')
plt.figure(figsize=(12,6))
plt.loglog(df['time'], df['delP'],'o', label='Differential Pressure dp')
plt.loglog(df['time'], df['Pdash'],'o', label = 'Derivative Pdash')
plt.xlabel('Time(log axis )')
plt.ylabel('Pressure (log axis)')
plt.title('Derivative plot / LOG-LOG plot/ Diagonestic plot : DRAWDOWN TEST')
plt.axvspan(1,100, color= 'blue', alpha = 0.2 , label = 'IARF')
plt.grid()
plt.legend ( )

from pandas.core.tools.times import time
from sklearn import linear_model
from sklearn.model_selection import train_test_split 
model= linear_model.LinearRegression()

import seaborn as sns
plt.loglog(df['time'], df['Pdash[10,10^2]'],'o', label = 'Derivative Pdash')
sns.lmplot(df['time'], df['Pdash'], data = df  )

ndf= df.drop('time', axis= 'columns')
ndf1= ndf.fillna(0)
plt.xlim(10,10^2)
ndf1

df1 = df.fillna(0)
df1

model= linear_model.LinearRegression()
model.fit(ndf1 ,df1.Pdash)

model.coef_

